package com.enyis.model;

import com.enyis.model.base.BaseProducts;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Products extends BaseProducts<Products> {
	public static final Products dao = new Products().dao();

	@Override
	String tableName() {
		// TODO Auto-generated method stub
		return "products";
	}

	@Override
	String primaryKey() {
		// TODO Auto-generated method stub
		return "proId";
	}

	@Override
	boolean isAutoId() {
		// TODO Auto-generated method stub
		return false;
	}
}
