package com.enyis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.enyis.model.AbstractModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseProducts<M extends BaseProducts<M>> extends AbstractModel<M> implements IBean {

	public M setProId(java.lang.String proId) {
		set("proId", proId);
		return (M)this;
	}

	public java.lang.String getProId() {
		return getStr("proId");
	}

	public M setProName(java.lang.String proName) {
		set("proName", proName);
		return (M)this;
	}

	public java.lang.String getProName() {
		return getStr("proName");
	}

	public M setLilterTitle(java.lang.String lilterTitle) {
		set("lilterTitle", lilterTitle);
		return (M)this;
	}

	public java.lang.String getLilterTitle() {
		return getStr("lilterTitle");
	}

	public M setProDetail(java.lang.String proDetail) {
		set("proDetail", proDetail);
		return (M)this;
	}

	public java.lang.String getProDetail() {
		return getStr("proDetail");
	}

	public M setMealAccId(java.lang.String mealAccId) {
		set("mealAccId", mealAccId);
		return (M)this;
	}

	public java.lang.String getMealAccId() {
		return getStr("mealAccId");
	}

	public M setProPrice(java.lang.String proPrice) {
		set("proPrice", proPrice);
		return (M)this;
	}

	public java.lang.String getProPrice() {
		return getStr("proPrice");
	}

	public M setAccId(java.lang.String accId) {
		set("accId", accId);
		return (M)this;
	}

	public java.lang.String getAccId() {
		return getStr("accId");
	}

	public M setSeContent(java.lang.String seContent) {
		set("seContent", seContent);
		return (M)this;
	}

	public java.lang.String getSeContent() {
		return getStr("seContent");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setStockpile(java.lang.String stockpile) {
		set("stockpile", stockpile);
		return (M)this;
	}

	public java.lang.String getStockpile() {
		return getStr("stockpile");
	}

	public M setSell(java.lang.String sell) {
		set("sell", sell);
		return (M)this;
	}

	public java.lang.String getSell() {
		return getStr("sell");
	}

	public M setLabel(java.lang.String label) {
		set("label", label);
		return (M)this;
	}

	public java.lang.String getLabel() {
		return getStr("label");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setThruDate(java.util.Date thruDate) {
		set("thruDate", thruDate);
		return (M)this;
	}

	public java.util.Date getThruDate() {
		return get("thruDate");
	}

	public M setLastUpdate(java.util.Date lastUpdate) {
		set("lastUpdate", lastUpdate);
		return (M)this;
	}

	public java.util.Date getLastUpdate() {
		return get("lastUpdate");
	}

}
