package com.enyis.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.enyis.model.AbstractModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseStandard<M extends BaseStandard<M>> extends AbstractModel<M> implements IBean {

	public M setStId(java.lang.String stId) {
		set("stId", stId);
		return (M)this;
	}

	public java.lang.String getStId() {
		return getStr("stId");
	}

	public M setProId(java.lang.String proId) {
		set("proId", proId);
		return (M)this;
	}

	public java.lang.String getProId() {
		return getStr("proId");
	}

	public M setStName(java.lang.String stName) {
		set("stName", stName);
		return (M)this;
	}

	public java.lang.String getStName() {
		return getStr("stName");
	}

	public M setStPrice(java.lang.String stPrice) {
		set("stPrice", stPrice);
		return (M)this;
	}

	public java.lang.String getStPrice() {
		return getStr("stPrice");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setThruDate(java.util.Date thruDate) {
		set("thruDate", thruDate);
		return (M)this;
	}

	public java.util.Date getThruDate() {
		return get("thruDate");
	}

	public M setLastUpdate(java.util.Date lastUpdate) {
		set("lastUpdate", lastUpdate);
		return (M)this;
	}

	public java.util.Date getLastUpdate() {
		return get("lastUpdate");
	}

}
