package com.enyis.model.base;

import com.enyis.model.AbstractModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseQin_Order<M extends BaseQin_Order<M>> extends AbstractModel<M> implements IBean {

	public M setOId(java.lang.String oId) {
		set("oId", oId);
		return (M)this;
	}

	public java.lang.String getOId() {
		return getStr("oId");
	}
	
	public M setMember(java.lang.String member) {
		set("member", member);
		return (M)this;
	}

	public java.lang.String getMember() {
		return getStr("member");
	}
	public M setProId(java.lang.String proId) {
		set("proId", proId);
		return (M)this;
	}

	public java.lang.String getProId() {
		return getStr("proId");
	}

	public M setUserId(java.lang.String userId) {
		set("userId", userId);
		return (M)this;
	}

	public java.lang.String getUserId() {
		return getStr("userId");
	}

	public M setDates(java.lang.String dates) {
		set("dates", dates);
		return (M)this;
	}

	public java.lang.String getDates() {
		return getStr("dates");
	}
	public M setStreet(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}

	public java.lang.Integer getNumber() {
		return getInt("number");
	}
	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setThruDate(java.util.Date thruDate) {
		set("thruDate", thruDate);
		return (M)this;
	}

	public java.util.Date getThruDate() {
		return get("thruDate");
	}

	public M setLastUpdate(java.util.Date lastUpdate) {
		set("lastUpdate", lastUpdate);
		return (M)this;
	}

	public java.util.Date getLastUpdate() {
		return get("lastUpdate");
	}

}
